nameOverride: skaffold-kubecontext-mismatch

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
ports:
  - name: http
    containerPort: 80
    protocol: TCP

service:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http

ingress:
  enabled: false